apiVersion: monitoring.coreos.co./v1
kind: PrometheusRule
metadata:
  name: self-heal-test-alert
  namespace: monitoring
spec:
  groups:
    - name: self-heal-test-group
      rules:
        - alert: SelfHealTestAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Self-heal test alert"
            description: "This is a test alert for Alertmanager webhook testing."
