apiVersion: v1
kind: Service 
metadata:
  name: remediation-serv-service
  labels:
    app: remediation-serv
spec:
  selector:
    app: remediation-serv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer