apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-serv-sa
  labels:
    app: remediation-serv
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::831274730062:role/self-heal-remediation-serv-role
  namespace: default
  