apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-heal-app-deployment
  labels:
    app: self-heal-app
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: self-heal-app
  template:
    metadata:
      labels:
        app: self-heal-app
    spec:
      containers:
      - name: self-heal-app
        image: 831274730062.dkr.ecr.us-east-1.amazonaws.com/self-heal-app:56cf50277ad638964ea7b8e2f6c6429adee779ea
        ports:
        - containerPort: 8000
